server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    microservice-provider-user:
      path: /user/**
      strip-prefix: false
    mdm:
      url: http://192.168.11.103:9110
      path: /mdm/**
      strip-prefix: false
  ignore-security-headers: false

# 禁用掉ribbon的eureka使用。详见：
# http://cloud.spring.io/spring-cloud-static/Camden.SR3/#_example_disable_eureka_use_in_ribbon
ribbon:
  eureka:
    enabled: false

microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000
    #listOfServers: localhost:8000,localhost:8001

logging:
  level:
    com.netflix: DEBUG